apiVersion: apps/v1
kind: Deployment
metadata:
  name: moglix-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moglix
  template:
    metadata:
      labels:
        app: moglix
    spec:
      containers:
      - name: my-app
        image: asia-south1-docker.pkg.dev/searce-playground-v1/moglix-test/demo-angular:tagversion
        ports:
        - containerPort: 4200
